config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  post 'tasks', to: 'tasks#create'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :compeleted)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'text'%>
    <%= f.text_field :title, class: 'input' %>
  </div>
  <div class="form-group">
    <%= f.label :details, class: 'text' %>
    <%= f.text_field :details, class: 'input' %>
   </div>
  <div class="form-group">
    <%= f.label :completed, class: 'text'%>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit "Submit", class: 'btn' %>
<% end %>

<%= link_to 'Back to all tasks', tasks_path, class: 'btn' %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
  <div class="box">
    <p>
    <% if task.completed == true %>
      <i class="far fa-check-square"></i>
    <% else %>
      <i class="far fa-square"></i>
    <% end %>
    <%= link_to task.title, task_path(task.id) %>
    <%= link_to task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="far fa-trash-alt"></i>
      <% end %>
    </p>
  </div>
<% end %>

<%= link_to 'Add a new task', tasks_new_path, class: 'btn' %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'text'%>
    <%= f.text_field :title, class: 'input' %>
  </div>
  <div class="form-group">
    <%= f.label :details, class: 'text' %>
    <%= f.text_field :details, class: 'input' %>
   </div>
  <div class="form-group">
    <%= f.label :completed, class: 'text'%>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit "Submit", class: 'btn' %>
<% end %>

<%= link_to 'Back to all tasks', tasks_path, class: 'btn' %>

app/views/tasks/show.html.erb
<h1>Your task</h1>

<h2> <%= @task.title %></h2>
<p><%= @task.details %></p>

<%= link_to 'Edit the task', edit_task_path(@task.id), class: 'btn' %>

<%= link_to 'Back to all tasks', tasks_path, class: 'btn' %>